---
name: dart_boilerplate
description: template repository for Dart project
publish_to: "none"
homepage: https://github.com/sensuikan1973/dart-boilerplate
repository: https://github.com/sensuikan1973/dart-boilerplate

version: 0.0.1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  meta: ^1.18.0

dev_dependencies:
  analyzer: ^10.0.1
  coverage: ^1.15.0 # See: https://github.com/dart-lang/test/issues/1265
  pedantic_sensuikan1973: ^5.16.0
  test: ^1.29.0
